versions_to_keep: 300
site_name_short: "World Mathaba"
site_name_long: "World Mathaba Independent News"
host: 'mathaba.dev'
cache_time: 86400
fragment_cache_time: 172800
google_plus_link: "https://plus.google.com/114360341024930120596"
facebook_link: "https://www.facebook.com/worldmathaba"
twitter_link: "https://twitter.com/worldmathaba"
flattr_link: "http://flattr.com/thing/631126/WorldMathaba"
from_email: "inbox@worldmathaba.net"
from_email_long: "inbox@worldmathaba.net"
reply_to_email: "inbox@worldmathaba.net"
google_analytics: "UA-00000000-0"
pingdom_status_page: "http://stats.pingdom.com/mph67nf90uv9/579615"